[package]
name = "topk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
divan = "0.1.14"
rand = "0.8"

[[bench]]
name = "topk"
harness = false
